# Generated by Django 2.2.5 on 2019-09-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190919_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='id',
        ),
        migrations.AlterField(
            model_name='autor',
            name='id_autor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='id_ent',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
