# Generated by Django 2.2.5 on 2019-09-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190919_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='apellidos_au',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nombres_au',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='autor_ent',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='contenido_ent',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='fecha_hora_ent',
            new_name='fecha_hora',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='titular_ent',
            new_name='titular',
        ),
    ]
